FOGL-2107 Updated README
foglamp/foglamp-south-opcua pull request #6
Opened 2018-11-26 09:42 UTC by MarkRiddoch

2018-11-26 10:09 UTC, Singhal-Vaibhav requested changes
The instructions are still not clear from a end user perspective. We are building the freeopcua library using `make`. That does not make the libraries available globally. Since our plugin is dependent on these libraries, we should provide an option in our plugin to search for opcua files in a particular location

2018-11-26 13:36 UTC, MarkRiddoch commented
Vaibhav, the object is not to "make the libraries available globally", it is to build the plugin.

Please elaborate on what is not clear here.

2018-11-27 12:13 UTC, Singhal-Vaibhav requested changes
1. Change required in environment variable name as mentioned in comment
2. Getting these warnings:
```
CMake Warning (dev) at CMakeLists.txt:64 (add_library):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "opcua" links to some libraries for which the linker must
  search:

    common-lib, -lpthread, -ldl

  and other libraries with known full path:

    /home/foglamp/Development/freeopcua/build/lib/libopcuaprotocol.so

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

After discussion with @AmandeepArora , if we use `cmake_minimum_required(VERSION 2.6.0)` in CMakeLists.txt, these warnings will go away

2018-11-27 12:13 UTC, Singhal-Vaibhav commented on README.rst
> +  $ export OPCUADIR=`pwd`
As per the script `set(OPCUADIR $ENV{FREEOPCUA})` it should be `export FREEOPCUA=...`

2018-11-27 15:18 UTC, Singhal-Vaibhav approved these changes
LGTM!!

2018-11-27 16:59 UTC, merged